import { defineConfig } from 'vite-plus';

export default defineConfig({
  staged: {
    '*': 'vp check --fix',
  },
  pack: {
    dts: true,
    exports: true,
  },
  lint: {
    plugins: ['typescript', 'unicorn', 'import'],
    categories: {
      correctness: 'error',
      suspicious: 'warn',
      perf: 'warn',
    },
    rules: {
      'no-console': [
        'warn',
        {
          allow: ['warn', 'error', 'info'],
        },
      ],
      'no-debugger': 'error',
      'no-var': 'error',
      'prefer-const': 'error',
      'eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
        },
      ],

      'typescript/no-floating-promises': 'error',
      'typescript/no-misused-promises': 'error',
      'typescript/await-thenable': 'error',
      'typescript/no-unsafe-assignment': 'warn',
      'typescript/require-await': 'warn',
      'typescript/restrict-template-expressions': 'warn',
      'typescript/unbound-method': 'error',
      'typescript/switch-exhaustiveness-check': 'warn',
      'typescript/prefer-nullish-coalescing': 'warn',
      'typescript/prefer-optional-chain': 'warn',
      'typescript/no-explicit-any': 'warn',
      'typescript/no-non-null-assertion': 'warn',
      'typescript/consistent-type-imports': 'warn',
      'typescript/consistent-type-exports': 'warn',
      'typescript/no-import-type-side-effects': 'error',
      'typescript/no-duplicate-enum-values': 'error',
      'typescript/no-duplicate-type-constituents': 'error',
      'typescript/no-redundant-type-constituents': 'error',
      'typescript/no-misused-spread': 'error',
      'typescript/no-base-to-string': 'error',
      'typescript/no-array-delete': 'error',
      'typescript/no-for-in-array': 'error',
      'typescript/no-meaningless-void-operator': 'error',
      'typescript/no-confusing-non-null-assertion': 'warn',
      'typescript/no-confusing-void-expression': 'warn',
      'typescript/ban-ts-comment': 'warn',
      'typescript/consistent-generic-constructors': 'warn',
      'typescript/consistent-indexed-object-style': 'warn',
      'typescript/array-type': 'warn',
      'typescript/no-inferrable-types': 'warn',
      'typescript/no-empty-object-type': 'warn',
      'typescript/no-invalid-void-type': 'warn',
      'typescript/no-dynamic-delete': 'warn',
      'typescript/no-namespace': 'warn',
      'typescript/no-require-imports': 'warn',
      'typescript/adjacent-overload-signatures': 'warn',

      'unicorn/no-instanceof-array': 'warn',
      'unicorn/no-invalid-fetch-options': 'error',
      'unicorn/no-invalid-remove-event-listener': 'error',
      'unicorn/no-thenable': 'error',
      'unicorn/no-await-in-promise-methods': 'error',
      'unicorn/catch-error-name': 'warn',
      'unicorn/error-message': 'warn',
      'unicorn/no-new-array': 'warn',
      'unicorn/no-null': 'off',
      'import/no-duplicates': 'error',
      'import/no-cycle': 'warn',
      'import/no-self-import': 'error',
      'import/no-mutable-exports': 'warn',
      'import/newline-after-import': 'warn',
    },
    options: {
      typeAware: true,
      typeCheck: true,
    },
  },
  fmt: {
    sortImports: {
      groups: [
        'type-import',
        'type-internal',
        ['type-parent', 'type-sibling', 'type-index'],
        ['value-builtin', 'value-external'],
        'value-internal',
        ['value-parent', 'value-sibling', 'value-index'],
        'unknown',
      ],
      newlinesBetween: false,
    },
    sortPackageJson: false,
    singleQuote: true,
  },
});
